# Name(s)
Clay Rosenthal

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [5]:
import numpy as np
a = np.full((6,4), 2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [6]:
b = 2 * np.eye(6,4) + np.ones((6,4))
print(b)

[[3. 1. 1. 1.]
 [1. 3. 1. 1.]
 [1. 1. 3. 1.]
 [1. 1. 1. 3.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Exercise 3
`a * b` works because it is actually multiplying the matrixes but `dot()` computes a dot product which needs the columns of the first to match the rows of the second


In [13]:
c = a * b
print(c)

[[6. 2. 2. 2.]
 [2. 6. 2. 2.]
 [2. 2. 6. 2.]
 [2. 2. 2. 6.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


## Exercise 4
they are not the same shape because one is multiplying a 4 x 6 by a 6 x 4 which gives a 4 x 4 and the other is multiplying a 6 x 4 by a 4 x 6 which gives a 6 x 6

In [15]:
atb = np.dot(a.transpose(), b)
print(atb)
abt = np.dot(a, b.transpose())
print(abt)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]


## Exercise 5

In [17]:
def printstuff():
    print('some output on the screen and make sure you can run it in the programming environment that you are using.')
printstuff()

some output on the screen and make sure you can run it in the programming environment that you are using.


## Exercise 6

In [21]:
def randomArrays():
    arr = np.random.rand(5,5)
    print(f"array: {arr}")
    print(f"sum: {arr.sum()}")
    print(f"mean: {arr.mean()}")
    print(f"standard deviation: {arr.std()}")
randomArrays()

array: [[0.29009811 0.78075624 0.52743207 0.54206187 0.53846373]
 [0.49852111 0.74809856 0.15135851 0.36441592 0.46301262]
 [0.58399524 0.98230465 0.79069518 0.1878305  0.33228193]
 [0.35189518 0.25947386 0.36853483 0.46688787 0.11778014]
 [0.59093426 0.71930134 0.37118052 0.48923071 0.40517002]]
sum: 11.921714982918168
mean: 0.4768685993167267
standard deviation: 0.20904019440979374


## Exercise 7

In [28]:
def loopOnes(arr):
    count = 0
    for elem in arr:
        if elem == 1:
            count += 1
    return count

def whereOnes(arr):
    return np.where(arr == 1, arr, 0).sum()

arr = np.array([1, 2, 0, 1, 4, 1, 3, 69, 1, 420])
print(f"loop: {loopOnes(arr)}")
print(f"where: {whereOnes(arr)}")


loop: 4
where: 4


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
import pandas as pd
p_a = pd.DataFrame()

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE